# Generated by Django 2.0.5 on 2018-05-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOMBRE')),
                ('lastname', models.CharField(max_length=50, verbose_name='APELLIDO')),
                ('position', models.CharField(max_length=100, verbose_name='POSITION')),
                ('telephone', models.CharField(max_length=9, verbose_name='Nº TELEFONO')),
                ('phone', models.CharField(max_length=9, verbose_name='Nº CELULAR')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='STRIA Y/O DIRECCIONES')),
                ('number', models.CharField(max_length=9, verbose_name='Nº TELEFONO')),
                ('fax', models.CharField(max_length=9, verbose_name='FAX')),
                ('address', models.CharField(max_length=50, verbose_name='DIRECCION')),
                ('location', models.URLField(max_length=500, verbose_name='UBICACION')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='STRIA Y/O DIRECCIONES')),
                ('number', models.CharField(max_length=9, verbose_name='Nº TELEFONO')),
                ('fax', models.CharField(max_length=9, verbose_name='FAX')),
                ('address', models.CharField(max_length=50, verbose_name='DIRECCION')),
                ('location', models.URLField(max_length=500, verbose_name='UBICACION')),
                ('secretaria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookphone.Secretaria', verbose_name='SECRETARIA')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookphone.Unidad', verbose_name='UNIDAD'),
        ),
    ]
