# Generated by Django 2.0.5 on 2018-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookphone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='location',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='location',
        ),
        migrations.AddField(
            model_name='secretaria',
            name='lat',
            field=models.CharField(default=1, max_length=50, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretaria',
            name='lng',
            field=models.CharField(default=1, max_length=50, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='lat',
            field=models.CharField(default=1, max_length=50, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='lng',
            field=models.CharField(default=1, max_length=50, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
