# Generated by Django 2.0.5 on 2018-07-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookphone', '0002_auto_20180710_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOMBRE')),
                ('lastname', models.CharField(max_length=50, verbose_name='APELLIDO')),
                ('position', models.CharField(max_length=100, verbose_name='POSITION')),
                ('telephone', models.CharField(max_length=9, verbose_name='Nº TELEFONO')),
                ('phone', models.CharField(max_length=9, verbose_name='Nº CELULAR')),
                ('secretaria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookphone.Secretaria', verbose_name='SECRETARIA')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOMBRE')),
                ('lastname', models.CharField(max_length=50, verbose_name='APELLIDO')),
                ('position', models.CharField(max_length=100, verbose_name='POSITION')),
                ('telephone', models.CharField(max_length=9, verbose_name='Nº TELEFONO')),
                ('phone', models.CharField(max_length=9, verbose_name='Nº CELULAR')),
                ('unidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookphone.Unidad', verbose_name='UNIDAD')),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='unidad',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
