# Generated by Django 2.0.7 on 2018-08-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookphone', '0003_auto_20180710_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='lat',
            field=models.CharField(blank=True, max_length=50, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='lng',
            field=models.CharField(blank=True, max_length=50, verbose_name='Longitud'),
        ),
    ]
