# Generated by Django 2.0.7 on 2018-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookphone', '0004_auto_20180808_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='lat',
            field=models.CharField(max_length=50, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='lng',
            field=models.CharField(max_length=50, verbose_name='Longitud'),
        ),
    ]
