# Generated by Django 2.0.7 on 2018-09-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookphone', '0005_auto_20180808_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_secretaria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_personal_secretaria/', verbose_name='Imagenn'),
        ),
    ]
