# Generated by Django 2.0.7 on 2018-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookphone', '0006_personal_secretaria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_secretaria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagen'),
        ),
    ]
