# Generated by Django 2.0.7 on 2018-09-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookphone', '0007_auto_20180905_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_secretaria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='FOTO'),
        ),
    ]
