# Generated by Django 2.0.7 on 2018-09-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookphone', '0008_auto_20180905_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_secretaria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='FOTO'),
        ),
    ]
